//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SADADUploadWindowsService.SADADUploadWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SADADUploadWebService.IIJARAHSADADUPLOAD")]
    public interface IIJARAHSADADUPLOAD {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIJARAHSADADUPLOAD/GetAndUploadAccountReceivables")]
        void GetAndUploadAccountReceivables();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, AsyncPattern=true, Action="http://tempuri.org/IIJARAHSADADUPLOAD/GetAndUploadAccountReceivables")]
        System.IAsyncResult BeginGetAndUploadAccountReceivables(System.AsyncCallback callback, object asyncState);
        
        void EndGetAndUploadAccountReceivables(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIJARAHSADADUPLOADChannel : SADADUploadWindowsService.SADADUploadWebService.IIJARAHSADADUPLOAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IJARAHSADADUPLOADClient : System.ServiceModel.ClientBase<SADADUploadWindowsService.SADADUploadWebService.IIJARAHSADADUPLOAD>, SADADUploadWindowsService.SADADUploadWebService.IIJARAHSADADUPLOAD {
        
        private BeginOperationDelegate onBeginGetAndUploadAccountReceivablesDelegate;
        
        private EndOperationDelegate onEndGetAndUploadAccountReceivablesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAndUploadAccountReceivablesCompletedDelegate;
        
        public IJARAHSADADUPLOADClient() {
        }
        
        public IJARAHSADADUPLOADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IJARAHSADADUPLOADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IJARAHSADADUPLOADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IJARAHSADADUPLOADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> GetAndUploadAccountReceivablesCompleted;
        
        public void GetAndUploadAccountReceivables() {
            base.Channel.GetAndUploadAccountReceivables();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAndUploadAccountReceivables(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAndUploadAccountReceivables(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndGetAndUploadAccountReceivables(System.IAsyncResult result) {
            base.Channel.EndGetAndUploadAccountReceivables(result);
        }
        
        private System.IAsyncResult OnBeginGetAndUploadAccountReceivables(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAndUploadAccountReceivables(callback, asyncState);
        }
        
        private object[] OnEndGetAndUploadAccountReceivables(System.IAsyncResult result) {
            this.EndGetAndUploadAccountReceivables(result);
            return null;
        }
        
        private void OnGetAndUploadAccountReceivablesCompleted(object state) {
            if ((this.GetAndUploadAccountReceivablesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAndUploadAccountReceivablesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAndUploadAccountReceivablesAsync() {
            this.GetAndUploadAccountReceivablesAsync(null);
        }
        
        public void GetAndUploadAccountReceivablesAsync(object userState) {
            if ((this.onBeginGetAndUploadAccountReceivablesDelegate == null)) {
                this.onBeginGetAndUploadAccountReceivablesDelegate = new BeginOperationDelegate(this.OnBeginGetAndUploadAccountReceivables);
            }
            if ((this.onEndGetAndUploadAccountReceivablesDelegate == null)) {
                this.onEndGetAndUploadAccountReceivablesDelegate = new EndOperationDelegate(this.OnEndGetAndUploadAccountReceivables);
            }
            if ((this.onGetAndUploadAccountReceivablesCompletedDelegate == null)) {
                this.onGetAndUploadAccountReceivablesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAndUploadAccountReceivablesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAndUploadAccountReceivablesDelegate, null, this.onEndGetAndUploadAccountReceivablesDelegate, this.onGetAndUploadAccountReceivablesCompletedDelegate, userState);
        }
    }
}
