//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentWindowsService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IIjarahSadadPaymentInsert")]
    public interface IIjarahSadadPaymentInsert {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIjarahSadadPaymentInsert/SadadPaymentInsert")]
        void SadadPaymentInsert();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIjarahSadadPaymentInsertChannel : PaymentWindowsService.ServiceReference1.IIjarahSadadPaymentInsert, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IjarahSadadPaymentInsertClient : System.ServiceModel.ClientBase<PaymentWindowsService.ServiceReference1.IIjarahSadadPaymentInsert>, PaymentWindowsService.ServiceReference1.IIjarahSadadPaymentInsert {
        
        public IjarahSadadPaymentInsertClient() {
        }
        
        public IjarahSadadPaymentInsertClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IjarahSadadPaymentInsertClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IjarahSadadPaymentInsertClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IjarahSadadPaymentInsertClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SadadPaymentInsert() {
            base.Channel.SadadPaymentInsert();
        }
    }
}
