//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadadInsertPayment.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMS", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendSMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicensePlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSReference {
            get {
                return this.SMSReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSReferenceField, value) != true)) {
                    this.SMSReferenceField = value;
                    this.RaisePropertyChanged("SMSReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string LicensePlateNo {
            get {
                return this.LicensePlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicensePlateNoField, value) != true)) {
                    this.LicensePlateNoField = value;
                    this.RaisePropertyChanged("LicensePlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMail", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendMail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicensePlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSubjectHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientsTo {
            get {
                return this.RecipientsToField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsToField, value) != true)) {
                    this.RecipientsToField = value;
                    this.RaisePropertyChanged("RecipientsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string RecipientsCc {
            get {
                return this.RecipientsCcField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsCcField, value) != true)) {
                    this.RecipientsCcField = value;
                    this.RaisePropertyChanged("RecipientsCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailReference {
            get {
                return this.EmailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailReferenceField, value) != true)) {
                    this.EmailReferenceField = value;
                    this.RaisePropertyChanged("EmailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LicensePlateNo {
            get {
                return this.LicensePlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicensePlateNoField, value) != true)) {
                    this.LicensePlateNoField = value;
                    this.RaisePropertyChanged("LicensePlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CustomSubjectHead {
            get {
                return this.CustomSubjectHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSubjectHeadField, value) != true)) {
                    this.CustomSubjectHeadField = value;
                    this.RaisePropertyChanged("CustomSubjectHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSRSms", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendSRSms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpportunityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SadadReferenceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSReference {
            get {
                return this.SMSReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSReferenceField, value) != true)) {
                    this.SMSReferenceField = value;
                    this.RaisePropertyChanged("SMSReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string OpportunityNumber {
            get {
                return this.OpportunityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OpportunityNumberField, value) != true)) {
                    this.OpportunityNumberField = value;
                    this.RaisePropertyChanged("OpportunityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string SadadReferenceNumber {
            get {
                return this.SadadReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SadadReferenceNumberField, value) != true)) {
                    this.SadadReferenceNumberField = value;
                    this.RaisePropertyChanged("SadadReferenceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSREmail", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendSREmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpportunityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSubjectHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SadadReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIBANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerBankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirtualAccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientsTo {
            get {
                return this.RecipientsToField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsToField, value) != true)) {
                    this.RecipientsToField = value;
                    this.RaisePropertyChanged("RecipientsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string RecipientsCc {
            get {
                return this.RecipientsCcField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsCcField, value) != true)) {
                    this.RecipientsCcField = value;
                    this.RaisePropertyChanged("RecipientsCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailReference {
            get {
                return this.EmailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailReferenceField, value) != true)) {
                    this.EmailReferenceField = value;
                    this.RaisePropertyChanged("EmailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string OpportunityNumber {
            get {
                return this.OpportunityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OpportunityNumberField, value) != true)) {
                    this.OpportunityNumberField = value;
                    this.RaisePropertyChanged("OpportunityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CustomSubjectHead {
            get {
                return this.CustomSubjectHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSubjectHeadField, value) != true)) {
                    this.CustomSubjectHeadField = value;
                    this.RaisePropertyChanged("CustomSubjectHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string SadadReferenceNumber {
            get {
                return this.SadadReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SadadReferenceNumberField, value) != true)) {
                    this.SadadReferenceNumberField = value;
                    this.RaisePropertyChanged("SadadReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string CustomerIBAN {
            get {
                return this.CustomerIBANField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIBANField, value) != true)) {
                    this.CustomerIBANField = value;
                    this.RaisePropertyChanged("CustomerIBAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string CustomerBankName {
            get {
                return this.CustomerBankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerBankNameField, value) != true)) {
                    this.CustomerBankNameField = value;
                    this.RaisePropertyChanged("CustomerBankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string VirtualAccount {
            get {
                return this.VirtualAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.VirtualAccountField, value) != true)) {
                    this.VirtualAccountField = value;
                    this.RaisePropertyChanged("VirtualAccount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSaleSMS", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendSaleSMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirtualAccntNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SADADRefNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarbrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ApplicationNum {
            get {
                return this.ApplicationNumField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNumField, value) != true)) {
                    this.ApplicationNumField = value;
                    this.RaisePropertyChanged("ApplicationNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DownPayment {
            get {
                return this.DownPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.DownPaymentField, value) != true)) {
                    this.DownPaymentField = value;
                    this.RaisePropertyChanged("DownPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string AdminFee {
            get {
                return this.AdminFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminFeeField, value) != true)) {
                    this.AdminFeeField = value;
                    this.RaisePropertyChanged("AdminFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string VirtualAccntNum {
            get {
                return this.VirtualAccntNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VirtualAccntNumField, value) != true)) {
                    this.VirtualAccntNumField = value;
                    this.RaisePropertyChanged("VirtualAccntNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string SADADRefNum {
            get {
                return this.SADADRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SADADRefNumField, value) != true)) {
                    this.SADADRefNumField = value;
                    this.RaisePropertyChanged("SADADRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string SMSReference {
            get {
                return this.SMSReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSReferenceField, value) != true)) {
                    this.SMSReferenceField = value;
                    this.RaisePropertyChanged("SMSReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string Totalamount {
            get {
                return this.TotalamountField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalamountField, value) != true)) {
                    this.TotalamountField = value;
                    this.RaisePropertyChanged("Totalamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Carbrand {
            get {
                return this.CarbrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CarbrandField, value) != true)) {
                    this.CarbrandField = value;
                    this.RaisePropertyChanged("Carbrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Numberplate {
            get {
                return this.NumberplateField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberplateField, value) != true)) {
                    this.NumberplateField = value;
                    this.RaisePropertyChanged("Numberplate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSaleEmail", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendSaleEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsCcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DownPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSubjectHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdminFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirtualAccntNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SADADRefNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalamountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarbrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberplateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientsTo {
            get {
                return this.RecipientsToField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsToField, value) != true)) {
                    this.RecipientsToField = value;
                    this.RaisePropertyChanged("RecipientsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string RecipientsCc {
            get {
                return this.RecipientsCcField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsCcField, value) != true)) {
                    this.RecipientsCcField = value;
                    this.RaisePropertyChanged("RecipientsCc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailReference {
            get {
                return this.EmailReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailReferenceField, value) != true)) {
                    this.EmailReferenceField = value;
                    this.RaisePropertyChanged("EmailReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ApplicationNum {
            get {
                return this.ApplicationNumField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNumField, value) != true)) {
                    this.ApplicationNumField = value;
                    this.RaisePropertyChanged("ApplicationNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DownPayment {
            get {
                return this.DownPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.DownPaymentField, value) != true)) {
                    this.DownPaymentField = value;
                    this.RaisePropertyChanged("DownPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CustomSubjectHead {
            get {
                return this.CustomSubjectHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSubjectHeadField, value) != true)) {
                    this.CustomSubjectHeadField = value;
                    this.RaisePropertyChanged("CustomSubjectHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string AdminFee {
            get {
                return this.AdminFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdminFeeField, value) != true)) {
                    this.AdminFeeField = value;
                    this.RaisePropertyChanged("AdminFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string VirtualAccntNum {
            get {
                return this.VirtualAccntNumField;
            }
            set {
                if ((object.ReferenceEquals(this.VirtualAccntNumField, value) != true)) {
                    this.VirtualAccntNumField = value;
                    this.RaisePropertyChanged("VirtualAccntNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string SADADRefNum {
            get {
                return this.SADADRefNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SADADRefNumField, value) != true)) {
                    this.SADADRefNumField = value;
                    this.RaisePropertyChanged("SADADRefNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Totalamount {
            get {
                return this.TotalamountField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalamountField, value) != true)) {
                    this.TotalamountField = value;
                    this.RaisePropertyChanged("Totalamount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Carbrand {
            get {
                return this.CarbrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CarbrandField, value) != true)) {
                    this.CarbrandField = value;
                    this.RaisePropertyChanged("Carbrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string Numberplate {
            get {
                return this.NumberplateField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberplateField, value) != true)) {
                    this.NumberplateField = value;
                    this.RaisePropertyChanged("Numberplate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPOSSMS", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendPOSSMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referencenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referencenumber {
            get {
                return this.referencenumberField;
            }
            set {
                if ((object.ReferenceEquals(this.referencenumberField, value) != true)) {
                    this.referencenumberField = value;
                    this.RaisePropertyChanged("referencenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string SMSReference {
            get {
                return this.SMSReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSReferenceField, value) != true)) {
                    this.SMSReferenceField = value;
                    this.RaisePropertyChanged("SMSReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IjarahOTPSMS", Namespace="http://schemas.datacontract.org/2004/07/MessagingGateway")]
    [System.SerializableAttribute()]
    public partial class IjarahOTPSMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicensePlateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpportunityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SadadReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicensePlateNo {
            get {
                return this.LicensePlateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.LicensePlateNoField, value) != true)) {
                    this.LicensePlateNoField = value;
                    this.RaisePropertyChanged("LicensePlateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpportunityNumber {
            get {
                return this.OpportunityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OpportunityNumberField, value) != true)) {
                    this.OpportunityNumberField = value;
                    this.RaisePropertyChanged("OpportunityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipients {
            get {
                return this.RecipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsField, value) != true)) {
                    this.RecipientsField = value;
                    this.RaisePropertyChanged("Recipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMSReference {
            get {
                return this.SMSReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSReferenceField, value) != true)) {
                    this.SMSReferenceField = value;
                    this.RaisePropertyChanged("SMSReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SadadReferenceNumber {
            get {
                return this.SadadReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SadadReferenceNumberField, value) != true)) {
                    this.SadadReferenceNumberField = value;
                    this.RaisePropertyChanged("SadadReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendBulkEmail", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SendBulkEmail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomSubjectHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpportunityNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecipientsCcField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientsTo {
            get {
                return this.RecipientsToField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsToField, value) != true)) {
                    this.RecipientsToField = value;
                    this.RaisePropertyChanged("RecipientsTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MessageCode {
            get {
                return this.MessageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageCodeField, value) != true)) {
                    this.MessageCodeField = value;
                    this.RaisePropertyChanged("MessageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTypeField, value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CustomMessage {
            get {
                return this.CustomMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomMessageField, value) != true)) {
                    this.CustomMessageField = value;
                    this.RaisePropertyChanged("CustomMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CustomSubjectHead {
            get {
                return this.CustomSubjectHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomSubjectHeadField, value) != true)) {
                    this.CustomSubjectHeadField = value;
                    this.RaisePropertyChanged("CustomSubjectHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string OpportunityNumber {
            get {
                return this.OpportunityNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OpportunityNumberField, value) != true)) {
                    this.OpportunityNumberField = value;
                    this.RaisePropertyChanged("OpportunityNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string SubjectN {
            get {
                return this.SubjectNField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectNField, value) != true)) {
                    this.SubjectNField = value;
                    this.RaisePropertyChanged("SubjectN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string SubjectU {
            get {
                return this.SubjectUField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectUField, value) != true)) {
                    this.SubjectUField = value;
                    this.RaisePropertyChanged("SubjectU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string RecipientsCc {
            get {
                return this.RecipientsCcField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipientsCcField, value) != true)) {
                    this.RecipientsCcField = value;
                    this.RaisePropertyChanged("RecipientsCc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IijaraMessagingGateway")]
    public interface IijaraMessagingGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSMSResponse")]
        string SendSMS(SadadInsertPayment.ServiceReference1.SendSMS ObjIjarahSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSMSResponse")]
        System.Threading.Tasks.Task<string> SendSMSAsync(SadadInsertPayment.ServiceReference1.SendSMS ObjIjarahSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendEMail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendEMailResponse")]
        void SendEMail(SadadInsertPayment.ServiceReference1.SendMail objIjarahEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendEMail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendEMailResponse")]
        System.Threading.Tasks.Task SendEMailAsync(SadadInsertPayment.ServiceReference1.SendMail objIjarahEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSRSms", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSRSmsResponse")]
        string SendSRSms(SadadInsertPayment.ServiceReference1.SendSRSms objIjarahSRSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSRSms", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSRSmsResponse")]
        System.Threading.Tasks.Task<string> SendSRSmsAsync(SadadInsertPayment.ServiceReference1.SendSRSms objIjarahSRSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSREmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSREmailResponse")]
        void SendSREmail(SadadInsertPayment.ServiceReference1.SendSREmail objIjarahSREmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSREmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSREmailResponse")]
        System.Threading.Tasks.Task SendSREmailAsync(SadadInsertPayment.ServiceReference1.SendSREmail objIjarahSREmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSaleSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSaleSMSResponse")]
        string SendSaleSMS(SadadInsertPayment.ServiceReference1.SendSaleSMS objIjarahSalesSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSaleSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSaleSMSResponse")]
        System.Threading.Tasks.Task<string> SendSaleSMSAsync(SadadInsertPayment.ServiceReference1.SendSaleSMS objIjarahSalesSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSaleEmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSaleEmailResponse")]
        void SendSaleEmail(SadadInsertPayment.ServiceReference1.SendSaleEmail objIjarahSalesEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendSaleEmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendSaleEmailResponse")]
        System.Threading.Tasks.Task SendSaleEmailAsync(SadadInsertPayment.ServiceReference1.SendSaleEmail objIjarahSalesEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendPOSSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendPOSSMSResponse")]
        string SendPOSSMS(SadadInsertPayment.ServiceReference1.SendPOSSMS objIjarahPOSSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendPOSSMS", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendPOSSMSResponse")]
        System.Threading.Tasks.Task<string> SendPOSSMSAsync(SadadInsertPayment.ServiceReference1.SendPOSSMS objIjarahPOSSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendOTP", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendOTPResponse")]
        string SendOTP(SadadInsertPayment.ServiceReference1.IjarahOTPSMS objIjarahOTPSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendOTP", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendOTPResponse")]
        System.Threading.Tasks.Task<string> SendOTPAsync(SadadInsertPayment.ServiceReference1.IjarahOTPSMS objIjarahOTPSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendBulkEmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendBulkEmailResponse")]
        void SendBulkEmail(SadadInsertPayment.ServiceReference1.SendBulkEmail objIjarahBulkEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IijaraMessagingGateway/SendBulkEmail", ReplyAction="http://tempuri.org/IijaraMessagingGateway/SendBulkEmailResponse")]
        System.Threading.Tasks.Task SendBulkEmailAsync(SadadInsertPayment.ServiceReference1.SendBulkEmail objIjarahBulkEmail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IijaraMessagingGatewayChannel : SadadInsertPayment.ServiceReference1.IijaraMessagingGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IijaraMessagingGatewayClient : System.ServiceModel.ClientBase<SadadInsertPayment.ServiceReference1.IijaraMessagingGateway>, SadadInsertPayment.ServiceReference1.IijaraMessagingGateway {
        
        public IijaraMessagingGatewayClient() {
        }
        
        public IijaraMessagingGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IijaraMessagingGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IijaraMessagingGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IijaraMessagingGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSMS(SadadInsertPayment.ServiceReference1.SendSMS ObjIjarahSMS) {
            return base.Channel.SendSMS(ObjIjarahSMS);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSAsync(SadadInsertPayment.ServiceReference1.SendSMS ObjIjarahSMS) {
            return base.Channel.SendSMSAsync(ObjIjarahSMS);
        }
        
        public void SendEMail(SadadInsertPayment.ServiceReference1.SendMail objIjarahEmail) {
            base.Channel.SendEMail(objIjarahEmail);
        }
        
        public System.Threading.Tasks.Task SendEMailAsync(SadadInsertPayment.ServiceReference1.SendMail objIjarahEmail) {
            return base.Channel.SendEMailAsync(objIjarahEmail);
        }
        
        public string SendSRSms(SadadInsertPayment.ServiceReference1.SendSRSms objIjarahSRSMS) {
            return base.Channel.SendSRSms(objIjarahSRSMS);
        }
        
        public System.Threading.Tasks.Task<string> SendSRSmsAsync(SadadInsertPayment.ServiceReference1.SendSRSms objIjarahSRSMS) {
            return base.Channel.SendSRSmsAsync(objIjarahSRSMS);
        }
        
        public void SendSREmail(SadadInsertPayment.ServiceReference1.SendSREmail objIjarahSREmail) {
            base.Channel.SendSREmail(objIjarahSREmail);
        }
        
        public System.Threading.Tasks.Task SendSREmailAsync(SadadInsertPayment.ServiceReference1.SendSREmail objIjarahSREmail) {
            return base.Channel.SendSREmailAsync(objIjarahSREmail);
        }
        
        public string SendSaleSMS(SadadInsertPayment.ServiceReference1.SendSaleSMS objIjarahSalesSMS) {
            return base.Channel.SendSaleSMS(objIjarahSalesSMS);
        }
        
        public System.Threading.Tasks.Task<string> SendSaleSMSAsync(SadadInsertPayment.ServiceReference1.SendSaleSMS objIjarahSalesSMS) {
            return base.Channel.SendSaleSMSAsync(objIjarahSalesSMS);
        }
        
        public void SendSaleEmail(SadadInsertPayment.ServiceReference1.SendSaleEmail objIjarahSalesEmail) {
            base.Channel.SendSaleEmail(objIjarahSalesEmail);
        }
        
        public System.Threading.Tasks.Task SendSaleEmailAsync(SadadInsertPayment.ServiceReference1.SendSaleEmail objIjarahSalesEmail) {
            return base.Channel.SendSaleEmailAsync(objIjarahSalesEmail);
        }
        
        public string SendPOSSMS(SadadInsertPayment.ServiceReference1.SendPOSSMS objIjarahPOSSMS) {
            return base.Channel.SendPOSSMS(objIjarahPOSSMS);
        }
        
        public System.Threading.Tasks.Task<string> SendPOSSMSAsync(SadadInsertPayment.ServiceReference1.SendPOSSMS objIjarahPOSSMS) {
            return base.Channel.SendPOSSMSAsync(objIjarahPOSSMS);
        }
        
        public string SendOTP(SadadInsertPayment.ServiceReference1.IjarahOTPSMS objIjarahOTPSMS) {
            return base.Channel.SendOTP(objIjarahOTPSMS);
        }
        
        public System.Threading.Tasks.Task<string> SendOTPAsync(SadadInsertPayment.ServiceReference1.IjarahOTPSMS objIjarahOTPSMS) {
            return base.Channel.SendOTPAsync(objIjarahOTPSMS);
        }
        
        public void SendBulkEmail(SadadInsertPayment.ServiceReference1.SendBulkEmail objIjarahBulkEmail) {
            base.Channel.SendBulkEmail(objIjarahBulkEmail);
        }
        
        public System.Threading.Tasks.Task SendBulkEmailAsync(SadadInsertPayment.ServiceReference1.SendBulkEmail objIjarahBulkEmail) {
            return base.Channel.SendBulkEmailAsync(objIjarahBulkEmail);
        }
    }
}
